// Publishes the custom SVG registry (Issue #8.1) as a plain JS module — a
// `name -> raw SVG markup string` map with no bundler contract at all: no
// `import.meta.glob`, no `?raw`/`?component` query, no `@` alias, no
// framework runtime. Any consumer (Vite, webpack, plain Node, an SSR
// server) gets the same object from `import { icons } from
// "@iam3xtr/ui/icons"` and decides for itself how to render the markup.
//
// The registry only ever contains this package's own custom icon set (LLM
// vendor logos, model-kind icons — see `src/assets/icons/*.svg`). It never
// duplicates Material Design Icons (that stays `@mdi/font`, applied by the
// consumer) and never depends on Vue/Buefy — mirroring the same tokens-only
// boundary `scripts/build.js` enforces for the CSS entrypoints.
//
// Source of truth stays the individual `.svg` files under
// `src/assets/icons/` (edit those, not the generated output); this script
// only compiles them into the one JS file `dist/icons.js` publishes, the
// same "src is the editable source, dist is the precompiled fallback"
// split `styles/tokens.css` / `styles/theme.css` already use.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const iconsDir = path.join(root, "src", "assets", "icons");
const distDir = path.join(root, "dist");

const names = readdirSync(iconsDir)
  .filter((file) => file.endsWith(".svg"))
  .map((file) => file.slice(0, -4))
  .sort();

const icons = {};
for (const name of names) {
  icons[name] = readFileSync(path.join(iconsDir, `${name}.svg`), "utf8").trim();
}

mkdirSync(distDir, { recursive: true });

const banner =
  "// Generated by scripts/build-icons.mjs from src/assets/icons/*.svg — do not edit by hand.\n";
const body = `export const icons = ${JSON.stringify(icons, null, 2)};\n\nexport default icons;\n`;
writeFileSync(path.join(distDir, "icons.js"), banner + body);

// eslint-disable-next-line no-console
console.log(`built dist/icons.js (${names.length} icons)`);
